Fix check_state

diff --git a/fabfunct b/fabfunct
--- a/fabfunct
+++ b/fabfunct
@@ -2,32 +2,30 @@
 error() {
 	echo;echo
 	echo "*****  Error in $1  *****"
-	cd $dir
-	logdir="$RUN_PREFIX/install_$(date | sed -e 's/  /_/g' -e 's/ /_/g')-faillogs"
-	mv $logs "$logdir"
-	echo "Logs can be found in '$logdir'"
-	cd ..
+	cd "$dir"
+	failog="$RUN_PREFIX/install_$(date | sed -e 's/  /_/g' -e 's/ /_/g')-faillogs"
+	mv "$logs" "$failog"
+	echo "Logs can be found in '$failog'"
 	exit 1
 }
 check_state() {
-	if [ -d "$RUN_PREFIX/install" ] || [ -f "$INSTALL_PREFIX/bin/construct" ]
+	if [ -f "$INSTALL_PREFIX/bin/construct" ]
 	then
 		echo "DETECTED"
 		if [ -d "$RUN_PREFIX/install/src" ]
 		then
 			echo "    Uninstalling current version..."
-			cdir=`pwd`
 			cd "$RUN_PREFIX/install/src"
-			make uninstall > $logs/uninstall.log 2>&1 || error "uninstalling the old copy"
-			cd ..
+			make uninstall > "$logs/uninstall.log" 2>&1 || error "uninstalling the old copy"
+			cd "$dir"
 			rm -fr src
 		else
 			echo "    Source files not found."
 			read -p "        Source directory: " src
-			if [ -d "$src" ]
+			if [ -f "$src/Makefile" ]
 			then
 				cd "$src"
-				make uninstall > $logs/uninstall.log 2>&1 || error "uninstalling the old copy"
+				make uninstall > "$logs/uninstall.log" 2>&1 || error "uninstalling the old copy"
 			else
 				echo 'Directory not found!'
 				exit 1
@@ -36,6 +34,7 @@ check_state() {
 	else
 		echo "NOT FOUND"
 		mkdir -p "$RUN_PREFIX/install"
+		rm -fr "$RUN_PREFIX/install/src"
 	fi
 }
 waitforproc() {
